### PR TITLE
Switch to using Xcode 9

### PR DESCRIPTION
**Pull request by mikew-personal**
#### Issue Summary

- Switch to using Xcode 9

#### Implementation Summary

- Updated the Circle CI yaml file for Xcode 9
- Updated the Xcode requirement for fastlane

### CODE REVIEW

**Comment by jasonhawkins** [comment]
This looks good, I was able to build and run without a problem. We may want to add a `.swift-verision` file too, but `pod install` is failing anyway because our Podfile seems to have some outdated targets in it. I know it's not strictly related to Xcode 9 / Swift 3.2 support but how do you feel about changing that for this PR?

**Comment by mikew-personal** [comment]
@jasonhawkins I'd rather address unrelated issues as a separate PR.  This PR is just meant to get us building using Xcode 9.

**Comment by jasonhawkins** [comment]
Alright, well in that case it _does_ build 👍

**Comment by mikew-personal** [comment]
@jasonhawkins Can you ticket the other issues you found in the frameworks backlog, I want to make sure we're tracking them.

**Comment by supperspidey** [comment]
@mikew-personal I was able to build and run, but uploading a video did not work for me. Should we open a separate ticket:
```
2017-10-06 16:44:27.614858-0400 VimeoUpload-iOS-OldUpload[31476:15999972] Task <860AACF3-B3A1-4AAD-B262-61C095945854>.<1> HTTP load failed (error code: -999 [1:89])
2017-10-06 16:44:27.614866-0400 VimeoUpload-iOS-OldUpload[31476:15999983] Task <860AACF3-B3A1-4AAD-B262-61C095945854>.<1> finished with error - code: -999
```
Both old upload and new upload exhibited those errors.

**Comment by mikew-personal** [comment]
@supperspidey This PR only changes CircleCI to build using Xcode 9 and changes the fast lane requirement for Xcode to be Xcode 9.  It doesn't address any existing issues with the framework.  If upload isn't working we should ticket that work in the frameworks backlog and address it in a separate ticket.

**Comment by supperspidey** [comment]
Ticket is ready https://vimean.atlassian.net/browse/AF-190

**Comment by nicolelehrer** [comment]
@supperspidey I was able to upload using old upload. When you have a sec, try again with your token to see if you get the same error.

**Pull request merged**
